# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

numNonZero <- function(x) {
    .Call('_scr_numNonZero', PACKAGE = 'scr', x)
}

scr_nll_acoustic <- function(pars, caps, traps, mask, maskDists, nCalls, toa, toa_ssq, use_toa, is_g0_fixed, g0_fixed, trace) {
    .Call('_scr_scr_nll_acoustic', PACKAGE = 'scr', pars, caps, traps, mask, maskDists, nCalls, toa, toa_ssq, use_toa, is_g0_fixed, g0_fixed, trace)
}

eucdist_nll <- function(points, traplocations) {
    .Call('_scr_eucdist_nll', PACKAGE = 'scr', points, traplocations)
}

scr_nll <- function(pars, caps, traps, mask, maskDists, binom) {
    .Call('_scr_scr_nll', PACKAGE = 'scr', pars, caps, traps, mask, maskDists, binom)
}

pointgen <- function(n = 50L, xlim = as.numeric( c(0, 100)), ylim = as.numeric( c(0, 100))) {
    .Call('_scr_pointgen', PACKAGE = 'scr', n, xlim, ylim)
}

make_toa_ssq <- function(capt, dists, sound_speed) {
    .Call('_scr_make_toa_ssq', PACKAGE = 'scr', capt, dists, sound_speed)
}

